spring:
  application:
    name: management

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-name: kakao
            client-id: ${Kakao_Client_ID}
            client-secret: ${Kakao_Client_SECRET}
            authorization-grant-type: authorization_code
            provider: kakao
            redirect-uri: ${Kakao_Redirect-URI}
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: never
  profiles:
    active: local
    include: secret-key
  datasource:
    url: jdbc:h2:tcp://localhost/~/management
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #    username: root
  #    password: ${DB_PASSWORD}
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://${SERVER_URL}:8001/db
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

#  data:
#    redis:

#      host: 127.0.0.1
#      port: 6379

  data:
    redis:
      cluster:
        nodes:
          - ${SERVER_URL}:${REDIS_MASTER_PORT_1},
          - ${SERVER_URL}:${REDIS_MASTER_PORT_2},
          - ${SERVER_URL}:${REDIS_MASTER_PORT_3},
        max-redirects: 3

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

server:
  port: 9000


